apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  namespace: headscale-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      labels:
        app: headscale
    spec:
      shareProcessNamespace: true
      serviceAccountName: default
      containers:
      - name: headplane
        image: ghcr.io/tale/headplane:0.6.0
        env:
        # Set these if the pod name for Headscale is not static
        # We will use the downward API to get the pod name instead
        - name: HEADPLANE_LOAD_ENV_OVERRIDES
          value: 'true'
        - name: 'HEADPLANE_INTEGRATION__KUBERNETES__POD_NAME'
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
          - containerPort: 3000
            name: headplane-ui
        volumeMounts:
          - name: headscale-config
            mountPath: /etc/headscale
            readOnly: true
          - name: headplane-config
            mountPath: /etc/headplane
            readOnly: true
          - name: headplane-data
            mountPath: /var/run/headplane
      - name: headscale
        image: ghcr.io/juanfont/headscale:latest
        command: ["headscale", "serve"]
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: headscale-secrets
              key: postgres-password
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 50443
          name: grpc
        - containerPort: 9090
          name: metrics
        - containerPort: 3478
          name: derp-stun
          protocol: UDP
        volumeMounts:
        - name: headscale-config
          mountPath: /etc/headscale
          readOnly: true
        - name: headscale-data
          mountPath: /var/lib/headscale
        - name: headscale-socket
          mountPath: /var/run/headscale
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: headscale-config
        configMap:
          name: headscale-config
      - name: headscale-data
        persistentVolumeClaim:
          claimName: headscale-data-pvc
      - name: headscale-socket
        emptyDir: {}
      - name: headplane-config
        configMap:
          name: headplane-config
      - name: headplane-data
        persistentVolumeClaim:
          claimName: headplane-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: headscale
  namespace: headscale-vpn
spec:
  selector:
    app: headscale
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 50443
    targetPort: 50443
  - name: metrics
    port: 9090
    targetPort: 9090
  - name: derp-stun
    port: 3478
    targetPort: 3478
    protocol: UDP
