apiVersion: v1
kind: Secret
metadata:
  name: headscale-secrets
  namespace: headscale-vpn
type: Opaque
stringData:
  postgres-password: "${POSTGRES_PASSWORD}"
  nordvpn-user: "${NORDVPN_USER}"
  nordvpn-pass: "${NORDVPN_PASS}"
  nordvpn-private-key: "${NORDVPN_WIREGUARD_KEY}"
  headscale-authkey: ""  # Will be populated dynamically by deploy script
