apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-db-pvc
  namespace: headscale-vpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: headscale-data-pvc
  namespace: headscale-vpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpn-exit-data-pvc
  namespace: headscale-vpn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
