# Traefik Helm Values
# Custom configuration for Traefik with Let's Encrypt ACME

# Use host networking for direct port access
hostNetwork: true

# Disable default service since we use hostNetwork
service:
  enabled: false

# Security context for running as root with NET_BIND_SERVICE
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 0

# Port configuration
ports:
  web:
    port: 80
    protocol: TCP
    hostPort: 80
  websecure:
    port: 443
    protocol: TCP
    hostPort: 443
    tls:
      enabled: true

# Provider configuration
providers:
  kubernetesIngress:
    publishedService:
      enabled: true

# Let's Encrypt ACME configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

# Deployment configuration
deployment:
  replicas: 1
  strategy:
    type: Recreate

# Persistent storage for ACME certificates
persistence:
  enabled: true
  size: 1Gi
  path: /data

# Enable dashboard
api:
  dashboard: true
  insecure: false

# Ingress class configuration
ingressClass:
  enabled: true
  isDefaultClass: true
