deployment:
  replicas: 1

# Security context for binding to privileged ports with hostNetwork
securityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

podSecurityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
      - NET_BIND_SERVICE
    drop: []
  
service:
  type: ClusterIP

hostNetwork: true

ports:
  web:
    port: 80
    hostPort: 80
    protocol: TCP
  websecure:
    port: 443
    hostPort: 443
    protocol: TCP

providers:
  kubernetesIngress:
    publishedService:
      enabled: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL:-admin@${DOMAIN}}
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
