deployment:
  replicas: 1
  
service:
  type: ClusterIP

hostNetwork: true

ports:
  web:
    port: 80
    hostPort: 80
    protocol: TCP
  websecure:
    port: 443
    hostPort: 443
    protocol: TCP

providers:
  kubernetesIngress:
    publishedService:
      enabled: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL:-admin@${DOMAIN}}
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
