# PersistentVolumeClaim for Traefik ACME storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-acme-storage
  namespace: traefik
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
