apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    hostNetwork: true
    service:
      enabled: false
    ports:
      web:
        port: 80
        expose: true
        protocol: TCP
      websecure:
        port: 443
        expose: true
        protocol: TCP
        tls:
          enabled: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    certificatesResolvers:
      letsencrypt:
        acme:
          email: admin@terranblake.com
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
