apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-exit-node
  namespace: headscale-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-exit-node
  template:
    metadata:
      labels:
        app: vpn-exit-node
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - "10.43.0.10"  # Cluster DNS
        searches:
          - "headscale-vpn.svc.cluster.local"
          - "svc.cluster.local"
          - "cluster.local"
        options:
          - name: ndots
            value: "2"
          - name: edns0
      containers:
      - name: gluetun
        image: qmcgaw/gluetun
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "custom"
        - name: VPN_TYPE
          value: "wireguard"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.42.0.0/16,10.43.0.0/16,100.64.0.0/10,10.43.0.10/32"
        - name: WIREGUARD_MTU
          value: "1280"
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        volumeMounts:
        - name: tun-device
          mountPath: /dev/net/tun
        - name: gluetun-data
          mountPath: /gluetun
        - name: vpn-config
          mountPath: /gluetun/wireguard
          readOnly: true
        ports:
        - containerPort: 8000
          name: control
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"  
            cpu: "100m"
      - name: tailscale
        image: tailscale/tailscale
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: headscale-secrets
              key: headscale-authkey
        - name: TS_STATE_DIR
          value: "/var/lib/tailscale"
        - name: TS_HOSTNAME
          value: "vpn-exit-node"
        - name: TS_EXTRA_ARGS
          value: "--login-server=http://headscale.headscale-vpn.svc.cluster.local:8080 --advertise-exit-node --accept-routes=false --accept-dns=false"
        - name: TS_USERSPACE
          value: "true"
        - name: TS_ACCEPT_DNS
          value: "false"
        - name: TS_KUBE_SECRET
          value: ""
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        volumeMounts:
        - name: vpn-exit-data
          mountPath: /var/lib/tailscale
        - name: tun-device
          mountPath: /dev/net/tun
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: vpn-exit-data
        persistentVolumeClaim:
          claimName: vpn-exit-data-pvc
      - name: gluetun-data
        persistentVolumeClaim:
          claimName: gluetun-data-pvc
      - name: tun-device
        hostPath:
          path: /dev/net/tun
      - name: vpn-config
        secret:
          secretName: vpn-exit-secrets
      nodeSelector:
        kubernetes.io/os: linux
