---
# Headscale configuration file
# https://headscale.net/ref/configuration/

# The server's URL (this will be used by clients to connect)
server_url: https://headscale.${DOMAIN}

# Address and port to listen on
listen_addr: 0.0.0.0:8080

# Address and port for the gRPC API
grpc_listen_addr: 0.0.0.0:50443

# Address and port for metrics
metrics_listen_addr: 0.0.0.0:9090

# Disable private key check warnings
private_key_path: /var/lib/headscale/private.key

# Disable noise warnings
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# IP prefixes for the mesh network
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

# Database configuration
database:
  type: postgres
  postgres:
    host: headscale-db
    port: 5432
    name: headscale
    user: headscale
    pass: ${POSTGRES_PASSWORD}
    max_open_conns: 10
    max_idle_conns: 10
    conn_max_idle_time: 3600s

# DERP configuration - self-hosted DERP server (no external Tailscale dependencies)
derp:
  server:
    enabled: true
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Self-Hosted DERP"
    stun_listen_addr: "0.0.0.0:3478"
    hostname: "headscale.${DOMAIN}"
    private_key_path: /var/lib/headscale/derp_server_private.key
    # TLS is handled by ingress, so disable it on the internal server
    tls_enabled: false
  
  # No external DERP servers - fully self-hosted
  urls: []
  
  # Paths to custom DERP map files
  paths: []
  
  # Disable auto update from external sources
  auto_update_enabled: false
  update_frequency: 24h

# Disable Tailscale's coordination servers completely
disable_check_updates: true

# Ephemeral node configuration
ephemeral_node_inactivity_timeout: 30m

# Node update check interval
node_update_check_interval: 10s

# DNS configuration
dns:
  # Override local DNS - force all clients to use specified DNS servers
  override_local_dns: true
  
  # Nameservers to use - these will be pushed to all clients
  # Use external DNS servers that will be routed through the VPN exit node
  nameservers:
    global:
      - 1.1.1.1     # Cloudflare DNS
      - 8.8.8.8     # Google DNS
      - 2606:4700:4700::1111  # Cloudflare IPv6
      - 2001:4860:4860::8888  # Google IPv6
  
  # Search domains
  search_domains: []
  
  # Magic DNS settings
  magic_dns: true
  base_domain: vpn.internal

# Logging configuration
log:
  format: text
  level: info

acl:
  mode: database

# ACL (Access Control List) configuration
policy:
  path: /etc/headscale/acl.hjson

# OIDC configuration (disabled by default)
oidc:
  only_start_if_oidc_is_available: false
  issuer: ""
  client_id: ""
  client_secret: ""
  scope: ["openid", "profile", "email"]
  extra_params: {}
  allowed_domains: []
  allowed_users: []

# Randomize client port (helps with NAT traversal)
randomize_client_port: false
